spring:
  datasource:
      url: jdbc:mysql://10.15.85.226:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
mybatis:
   mapperLocations: classpath:/mapper/*.xml
