spring:
  datasource:
      url: jdbc:mysql://39.106.223.102:3306/mysql?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: lhj
      password: Lhj@12345
mybatis:
   mapperLocations: classpath:/mapper/*.xml
